### ISSUE TITLE
Support for Tex-based Equation Rendering?

### ISSUE THREAD

**Issue by ter-li** [syy11cn/hexo-theme-linear#2]
Hi, Yiyang,

Firstly, thanks for the excellent beauty work. It really stunned me.

Many people they use their blog for some paper review record, and the equation noting is of vital necessity.

So, along with that, there is a stupid question from me. Does this theme template support tex-based markdown equation rendering?  

If not, is there any plan for adding this feature? Looking forward to your reply.

Best, 
Teng

**Comment by syy11cn** [comment]
@ter-li Thx for your suggestion. It's a good idea to add tex support. Unfortunately, I don't know how to add it to a hexo theme. Could you please tell me some other themes with this feature. I will learn and try my best to add this feature.

**Comment by ter-li** [comment]
Thanks for your reply.

I know that the [next-theme](https://github.com/next-theme)/[hexo-theme-next](https://github.com/next-theme/hexo-theme-next) gives several options for [Math Formulas Render](https://github.com/next-theme/hexo-theme-next/blob/e16688573bc37dd1ec3b640991ea8d054e99c68a/_config.yml#L503). Hope can help you.

Last, thanks for your open-source contributions.

**Comment by syy11cn** [comment]
@ter-li Hey bro, the next theme is really a good example. I found them using Mathjax and Katex for tex parsing and displaying. I've tried out the sdks in my localhost demo, and it did work. I'll push the update to this repo later.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/57290456/159118434-ae771edf-dc0e-4c40-93a9-fcf5e5ded77b.png">

BTW, there are some bugs in the theme, mainly because of the busuanzi sdk. It's loading of pv is taking time. I'll consider a better way of pv and comment counting, or just move theme out of the theme.

I'll appreciate it if you like this hexo theme.

Best wishes!
